name: verified-links-2024

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  verified-links2024:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Update verified-links2024.txt
        run: |
              echo "$(date -u +'%Y-%m-%d %H:%M:%S') UTC - Update" >> verified-links2024.txt
          
      - name: Commit changes
        run: |
          git config --global user.email "isabellacosta134@hotmail.com"
          git config --global user.name "warriorcinsta"
          git add verified-links2024.txt
          git commit -m "verified-links2024.txt" || echo "No changes to commit"
          git push
